version: '3.8'
services:
  backend:
    build: .
    ports: 
    - "3000:3000" 
    volumes:
      - ./:/app
      - /app/node_modules
    restart: on-failure
  db: 
    image: postgres:15.0-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mspr
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
    driver: local